### Requête en local ###

###
# Récupérer une liste
GET http://localhost:3000/list/26

###
# Récupérer les contacts d'une liste
GET http://localhost:3000/list/contact/26

###
# Créer une list de contact
POST http://localhost:3000/list/create
content-type: application/json

{
    "name": "Nico",
    "description": "Nicolas"
}

###
# Ajouter un contact dans une liste
POST http://localhost:3000/list/update/26/add/1
content-type: application/json

###
# Supprimer un contact d'une liste
POST http://localhost:3000/list/update/1/remove/1
content-type: application/json

###
# Suppression d'une liste
DELETE http://localhost:3000/list/delete/25
content-type: application/json
