### Requête en local ###

###
# Récupérer l'ensemble des messages
GET http://localhost:3000/message/list

###
# Récupérer les messages d'un utilisateur
GET http://localhost:3000/message/list/user/1

###
# Créer un message
POST http://localhost:3000/message/brouillon
content-type: application/json

{
    "object": "true",
    "content": "Test"
}

###
# Préparer un message
POST http://localhost:3000/message/prepare
content-type: application/json

{
    "id": 51
}

###
# Envoyer un message
PATCH http://localhost:3000/message/send
content-type: application/json

{
    "id": 33
}

###
# Modifier un message
PATCH http://localhost:3000/message/update
content-type: application/json

{
    "id": 2,
    "content": "Roooo"
}

###
# Supprimer un message
DELETE http://localhost:3000/message/delete
content-type: application/json

{
    "id": 1
}


