### Requête en local ###

###
# Récupérer l'ensemble des messages
GET http://localhost:3000/message/list

###
# Récupérer les messages d'un utilisateur
GET http://localhost:3000/message/list/user/1

###
# Créer un message
POST http://localhost:3000/message/send
content-type: application/json

{
    "object": "true",
    "content": 1,
    "sendDate": "12",
    "sendHour": "12"
}

###
# Créer un message
PATCH http://localhost:3000/message/send
content-type: application/json

{
    "object": "true",
    "content": 1,
    "sendDate": "12",
    "sendHour": "12"
}

###
# Modifier un message
PATCH http://localhost:3000/message/update
content-type: application/json

{
    "id": 1,
    "content": "",
    "object": ""
}

###
# Modifier un message
DELETE http://localhost:3000/message/delet
content-type: application/json

{
    "id": 1,
    "content": ""
}


